# This file generates the GitHub Actions matrix for custom board and shield
# You can add multiple board+shield combinations under `include` if needed

---
include:
  - board: holyiot-18010-nRF52840
    shield: obscura60
