manifest:

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hnbn
      url-base: https://github.com/HNBN9

  projects:
    - name: zmk
      remote: hnbn
      revision : with-bootkey
      import: app/west.yml

    - name: zmkconf
      remote: hnbn
      revision: master 

  self:
    path: config
