manifest:
  defaults:
    revision: v0.2

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hnbn
      url-base: https://github.com/HNBN9

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml

    - name: zmkconf
      remote: hnbn
      revision: main  
      path: zmkconf    

  self:
    path: config
